### ISSUE TITLE
which thesis can be refered for your opensource code?

### ISSUE THREAD

**Issue by crankler** [lorenwel/octomap_compare#2]
Hi, thank you for your share of this code,
I'm still focus on the change of the dynamic point cloud,
can you tell me where can I get the thesis you refered about this code?

**Comment by lorenwel** [comment]
Hi, thanks for the interest in this work.
If you want to cite this, please use the following publication:
```
@inproceedings{wellhausen2017reliable,
  title={Reliable real-time change detection and mapping for 3d lidars},
  author={Wellhausen, Lorenz and Dub{\'e}, Renaud and Gawel, Abel and Siegwart, Roland and Cadena, Cesar},
  booktitle={2017 IEEE International Symposium on Safety, Security and Rescue Robotics (SSRR)},
  pages={81--87},
  year={2017},
  organization={IEEE}
}
```

**Comment by crankler** [comment]
Thank you for your reply!  Absolutely, I will cite your work.
At now, I will check and learn your code,  and again appreciate for your share.
